[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "radics-riscv-book"
authors = [{name = "Aziz Faozi", email = "aziz.faozi@radicstech.com"}]
dynamic = ["version", "description"]
